/**
 * ═══════════════════════════════════════════════════════════════════
 * CONSTANTS — Derived from siteConfig.ts
 * ═══════════════════════════════════════════════════════════════════
 * 
 * DO NOT EDIT THIS FILE to change business data.
 * Edit siteConfig.ts instead — this file reads from it automatically.
 * 
 * This file maps config icon names to actual Lucide components
 * and re-exports everything in the format pages expect.
 * ═══════════════════════════════════════════════════════════════════
 */

import {
  Wrench, Clock, ShowerHead, Shield, CheckCircle2, Droplets,
  Hammer, Flame, Thermometer, Pipette, Settings, Zap,
  type LucideIcon
} from 'lucide-react';
import siteConfig from './siteConfig';

// ── Icon Registry ──────────────────────────────────────────────────
// Maps icon name strings from siteConfig to actual Lucide components.
// Add more icons here as needed.
const ICON_MAP: Record<string, LucideIcon> = {
  Wrench,
  Clock,
  ShowerHead,
  Shield,
  CheckCircle2,
  Droplets,
  Hammer,
  Flame,
  Thermometer,
  Pipette,
  Settings,
  Zap,
};

function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] || Wrench;
}

// ── Re-exports (pages import from here) ────────────────────────────

export const COMPANY = siteConfig.company;
export const HERO = siteConfig.hero;
export const ABOUT = siteConfig.about;
export const TRUST_BADGES = siteConfig.trustBadges;
export const NAV_ITEMS = siteConfig.navigation;
export const STATS = siteConfig.stats;
export const PRODUCTS = siteConfig.products;
export const REVIEWS = siteConfig.reviews;
export const REFERENCES = siteConfig.references;
export const SERVICE_AREAS = siteConfig.serviceAreas;
export const PRICING_INFO = siteConfig.pricing;
export const COLORS = siteConfig.colors;
export const SEO = siteConfig.seo;

// Services — resolve icon names to actual components
export const SERVICES_SUMMARY = siteConfig.services.summary.map((s) => ({
  ...s,
  icon: getIcon(s.iconName),
}));

export const SERVICES_FULL = siteConfig.services.fullList;
export const SERVICES_PAGE_INTRO = siteConfig.services.pageIntro;

// Guarantees — resolve icon names to actual components
export const GUARANTEES = siteConfig.guarantees.map((g) => ({
  ...g,
  icon: getIcon(g.iconName),
}));
